### ISSUE TITLE
Cannot Assign a Worker to a WorkAssignment in Dispatch

### ISSUE THREAD

**Issue by chaim1221** [SavageLearning/Machete#140]
![image](https://cloud.githubusercontent.com/assets/3819970/22631241/4d30f596-ebbd-11e6-92d5-a628f339583b.png)

Steps to reproduce
==================

1. Create a Person, and make them a Worker.
2. Sign them in via the WorkerSignins page.
3. Create an Employer, and a Work Order, with one or more Assignments.
4. On the Dispatch tab, click the Worker, and the Assignment, and click the Assign button.
5. Worker is not assigned and the error message is shown. Clicking "OK" does not work.

**Comment by jcii** [comment]
Explaining this will give background on the refactor:

Machete had mappings in each controller for the AjaxHandler action, which was basically the default GET list for the entity, in REST terms. These mappings grew organically in the controller has more fields were needed. A lot of aggregation and Lookup mapping happened here. All of this mapping is integral to Machete and needs to be available for the WebAPI/Angular app as well. Thus, the refactor.

Refactoring these mappings into their own objects allows me to reuse them as we progress into WebAPI and angular land. The mappings have been split into two layers. the **Machete.Service.DTO** (data transfer object) object is for aggregation. It has access to the EF context by way of the IQueryable objects. Fancy stuff with EF should happen here so that it's available to the WebAPI consumer. This layer should push computation to the DB via SQL. 

The **Machete.Web.ViewModel** object is for formatting and conversion. Constructing fields specific for the MVC razor pages should happen here.  With the WebAPI version, there will be similar maps that contain this functionality, plus HATEOAS links. 

The maps themselves are currently in Machete.Web.Maps space. The DTO maps will have to be split out, but I haven't needed it yet, so I haven't done it.

**Comment by jcii** [comment]
As to the actual error reported, the `waid` field wasn't properly mapped. This has been the most time consuming part of the refactor.

**Comment by chaim1221** [comment]
fixed and working in `master` as of 2017-02-11
