### ISSUE TITLE
Platform: Add IdentityServer and machete-ui websites for active centers

### ISSUE THREAD

**Issue by chaim1221** [SavageLearning/Machete#380]

**Comment by jcii** [comment]
This is a huge task: I think the progression to reach this is:
1. Complete GH311 so that memory footprint of worker processes is not 1GB
2. Port to .NetCore
3. Deploy using Kubernetes clusters

You can skip 2 & 3 and deploy in IIS land, but we really have to do #1. Centers complain if the idle timeout lets the worker processes die (because it takes ~60 seconds to start a cold site). Leaving the processes running quickly leads to gargantuan worker processes. The Splunk site has a graph of it.

**Comment by chaim1221** [comment]
This is kind of a moot point now, as when https://github.com/chaim1221/Machete/pull/4 is merged, they will all be one process.
